name: test and publish

on:
  push:
    branches:
      - main  # Run on push to the main branch
    tags:
      - "v*.*.*"  # Run when a version tag is pushed

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest huggingface_hub
          pip install .  # Install the package locally for testing

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Run tests
        run: pytest tests/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: test  # Run only if the test job succeeds
    if: startsWith(github.ref, 'refs/tags/v')  # Execute only when a version tag is pushed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine huggingface_hub

      - name: Authenticate with Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token $HF_TOKEN

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}  # Use actual PyPI API token
        run: twine upload --repository pypi dist/*